# proto-file: compression_config.proto
# proto-message: CompressionConfig

primary_log_coder {
  residue_log_link_coder {
  }
  greedy_move_to_front_2_storage {
    static_movement_degree: 1
  }
  ngram_log_filter {
    n: 2
    acceptance_threshold: 0.4
  }
  storage_size: 255
  min_link_length: 6
}

secondary_log_coder {
  residue_secondary_log_coder {
  }
}

generic_primary_coder {
  bwt_modelling_coder {
    context_size: 2
    chunk_size: 1000000
    static_movement_degree: 1
  }
}

generic_secondary_coder {
  bwt_modelling_coder {
    context_size: 2
    chunk_size: 1000000
    static_movement_degree: 1
  }
}

generic_markup_coder {
  bwt_modelling_coder {
    context_size: 2
    chunk_size: 1000000
    static_movement_degree: 1
  }
}
