# proto-file: compression_config.proto
# proto-message: CompressionConfig

primary_log_coder {
  residue_log_link_coder {  # Directly specify the field inside the `oneof`
  }
  greedy_sliding_window_storage {  # Directly specify the field inside the `oneof`
  }
  storage_size: 256
  min_link_length: 4
}

secondary_log_coder {
  ppm_secondary_log_coder {  # Directly specify the field inside the `oneof`
    window_size: 128
  }
}

generic_primary_coder {
  modelling_coder {
    context_size: 5
  }
}

generic_secondary_coder {
  identity_coder {
  }
}

generic_markup_coder {
  modelling_coder {
    context_size: 3
  }
}
