# proto-file: compression_config.proto
# proto-message: CompressionConfig

primary_log_coder {
  residue_log_link_coder {
  }
  greedy_move_to_front_2_storage {
  }
  storage_size: 255
  min_link_length: 10
}

secondary_log_coder {
  ppm_secondary_log_coder {
    window_size: 3
  }
}

generic_primary_coder {
  bwt_modelling_coder {
    context_size: 3
    chunk_size: 900000
  }
}

generic_secondary_coder {
  identity_coder {
  }
}

generic_markup_coder {
  bwt_modelling_coder {
    context_size: 3
    chunk_size: 900000
  }
}
