name: C++ CI with Catch2

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install CMake, g++, and make
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Install Catch2 from source
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install

      - name: Configure CMake
        run: cmake -B build -S v2 -DCMAKE_BUILD_TYPE=Release
        working-directory: ${{ github.workspace }}

      - name: Build
        run: cmake --build build -- -j2
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: ./build/tests
        working-directory: ${{ github.workspace }}
